feat: 🎸 Add dwall & update aur publish

diff --git a/.github/workflows/_CD-AUR.yml b/.github/workflows/_CD-AUR.yml
--- a/.github/workflows/_CD-AUR.yml
+++ b/.github/workflows/_CD-AUR.yml
@@ -17,31 +17,106 @@ on:
           - "['oh-my-posh-bin']"
 
 jobs:
-  publish-aur:
+  generate-matrix:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Generate matrix
+        id: gen-matrix
+        run: echo "::set-output name=packages::$(find ./packages/ -type f -name '*PKGBUILD' | sed -r 's|/[^/]+$||' | sort | uniq | cut -f3 -d'/' | jq -R | jq -cs)"
+    outputs:
+      packages: ${{ steps.gen-matrix.outputs.packages }}
+
+  aur:
+    runs-on: ubuntu-latest
+    needs: generate-matrix
     strategy:
       fail-fast: false
       matrix:
-        pkgname: ${{ fromJSON(format('{0}{1}', github.event.inputs.packages, inputs.packages)) }}
-    runs-on: ubuntu-latest
+        pkgname: ${{ fromJson(needs.generate-matrix.outputs.packages) }}
+
     steps:
       - name: 📚 Checkout
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
-      - name: 🔧 Run update script
-        id: updatePKGs
-        run: |
-          bash update-pkg.sh ${{ matrix.pkgname }}
-      - name: 🔃 Get package version
-        run: |
-          source packages/${{ matrix.pkgname }}/PKGBUILD
-          echo "PKGVER=$pkgver" >> $GITHUB_ENV
-      - name: 🚀 Publish AUR package
-        uses: KSXGitHub/github-actions-deploy-aur@master
+
+      - name: Install SSH key
+        uses: shimataro/ssh-key-action@v2
         with:
-          pkgname: ${{ matrix.pkgname }}
-          pkgbuild: ./packages/${{ matrix.pkgname }}/PKGBUILD
-          commit_username: ${{ secrets.AUR_USERNAME }}
-          commit_email: ${{ secrets.AUR_EMAIL }}
-          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
-          commit_message: Update ${{ matrix.pkgname }} package to ${{ env.PKGVER }}
+          key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
+          known_hosts: ${{ secrets.KNOWN_HOSTS }}
+
+      - name: Check PKGBUILD
+        id: build-test
+        uses: ouuan/pkgbuild-action@f2b314d7fd3bfbe8432ca42da2f37b1fa9a208d2
+        with:
+          path: ${{ matrix.pkgname }}
+
+      - name: Handle epoch
+        id: epoch
+        run: |
+          oldname="${{ steps.build-test.outputs.pkgfile }}"
+          newname="$(echo "$oldname" | sed -e 's/[^A-Za-z0-9._-]/_/g')"
+          if [[ "$oldname" != "$newname" ]]; then
+            mv "$oldname" "$newname"
+          fi
+          echo "::set-output name=pkgfile::$newname"
+
+      - uses: actions/upload-artifact@v2
+        with:
+          name: ${{ matrix.pkgname }}-${{ github.run_id }}
+          path: ${{ steps.epoch.outputs.pkgfile }}
+
+      - name: Clone AUR and update
+        run: |
+          message="$(git log -n1 --pretty='%B' "${{ matrix.pkgname }}")"
+          git clone ssh://aur@aur.archlinux.org/${{ matrix.pkgname }}.git ../aur
+          shopt -s dotglob
+          shopt -s extglob
+          rm ../aur/!(.git|.|..) || true
+          cp -r ${{ matrix.pkgname }}/*  ../aur
+          cd ../aur
+          git config user.name "GitHub Action"
+          git config user.email "action@github.com"
+          git add -A
+          escape() {
+            local content="$1"
+            content="${content//'%'/'%25'}"
+            content="${content//$'\n'/'%0A'}"
+            content="${content//$'\r'/'%0D'}"
+            echo "$content"
+          }
+          git diff-index @ --exit-code --quiet || ( git commit -m "Update from GitHub Actions: $message
+
+          https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}" && echo "::warning::Pushed to AUR:%0A$(escape "$message")" )
+          git push
+
+  # publish-aur:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       pkgname: ${{ fromJSON(format('{0}{1}', github.event.inputs.packages, inputs.packages)) }}
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: 📚 Checkout
+  #       uses: actions/checkout@v2
+  #       with:
+  #         fetch-depth: 0
+  #     - name: 🔧 Run update script
+  #       id: updatePKGs
+  #       run: |
+  #         bash update-pkg.sh ${{ matrix.pkgname }}
+  #     - name: 🔃 Get package version
+  #       run: |
+  #         source packages/${{ matrix.pkgname }}/PKGBUILD
+  #         echo "PKGVER=$pkgver" >> $GITHUB_ENV
+  #     - name: 🚀 Publish AUR package
+  #       uses: KSXGitHub/github-actions-deploy-aur@master
+  #       with:
+  #         pkgname: ${{ matrix.pkgname }}
+  #         pkgbuild: ./packages/${{ matrix.pkgname }}/PKGBUILD
+  #         commit_username: ${{ secrets.AUR_USERNAME }}
+  #         commit_email: ${{ secrets.AUR_EMAIL }}
+  #         ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
+  #         commit_message: Update ${{ matrix.pkgname }} package to ${{ env.PKGVER }}
